Repository Abhinandan-git/mini-project, pull requests merged in 2023-11, with the labels that each got.

#2 Bugfix middleware and babel
  client/package-lock.json
  client/package.json
Labels: bugfix

#4 Added buttons
  client/src/App.css
  client/src/App.js
  client/src/components/Buttons.js
  client/src/components/Functions.js
  client/src/components/css/Buttons.css
  client/src/components/css/common.css
  client/src/index.css
Labels: feature

#5 Feature material card wrapper
  client/src/App.js
  client/src/components/MaterialCard.js
  client/src/components/MaterialCardsWrapper.js
  client/src/components/css/MaterialCard.css
  client/src/components/css/MaterialCardsWrapper.css
  client/src/index.js
Labels: feature

#6 Changed public files
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/logo.svg
Labels: documentation, structure

#7 Added basic server structure
  client/.gitignore
  client/src/components/MaterialCardsWrapper.js
  server/.gitignore
  server/node_modules/.package-lock.json
  server/node_modules/dotenv/CHANGELOG.md
  server/node_modules/dotenv/LICENSE
  server/node_modules/dotenv/README-es.md
  server/node_modules/dotenv/README.md
  server/node_modules/dotenv/config.d.ts
  server/node_modules/dotenv/config.js
  server/node_modules/dotenv/lib/cli-options.js
  server/node_modules/dotenv/lib/env-options.js
  server/node_modules/dotenv/lib/main.d.ts
  server/node_modules/dotenv/lib/main.js
  server/node_modules/dotenv/package.json
  server/package-lock.json
  server/package.json
  server/server.js
Labels: bugfix, feature, structure

#8 Structure directories
  .gitignore
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/components/MaterialCardsWrapper.js
  server/.gitignore
  server/server.js
Labels: bugfix, documentation, structure

#9 Server and Client work | inventory wrapper completed
  .gitignore
  client/src/components/MaterialCardsWrapper.js
  server/.gitignore
  server/server.js
Labels: documentation, feature, structure

#10 Server and Client connected and Changed port
  .gitignore
  package-lock.json
  package.json
  server/server.js
Labels: bugfix, feature, structure

#11 Bugfix inventory save
  client/src/App.js
  client/src/components/Buttons.js
  client/src/components/Functions.js
  client/src/components/MaterialCardsWrapper.js
  client/src/index.js
Labels: bugfix

#12 Storing url as env
  server/server.js
Labels: bugfix

#13 Loading screen
  client/src/components/Loading.js
  client/src/components/MaterialCardsWrapper.js
  client/src/components/css/Loading.css
Labels: feature

#15 Bugfix random order data
  client/src/components/Functions.js
  client/src/components/Loading.js
  client/src/components/MaterialCardsWrapper.js
Labels: bugfix

#16 Added basic item card
  client/src/components/ItemCard.js
Labels: feature, structure

#18 Feature server write database
  client/src/components/MaterialCardsWrapper.js
  server/node_modules/.package-lock.json
  server/node_modules/body-parser/HISTORY.md
  server/node_modules/body-parser/README.md
  server/node_modules/body-parser/lib/types/json.js
  server/node_modules/body-parser/package.json
  server/node_modules/raw-body/HISTORY.md
  server/node_modules/raw-body/README.md
  server/node_modules/raw-body/index.js
  server/node_modules/raw-body/package.json
  server/package-lock.json
  server/package.json
  server/server.js
Labels: bugfix, feature, help
